version: '3.8'

services:
  cesizen_db:
    container_name: cesizen_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASSWORD:-Strong!Passw0rd}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cesizen_api:
    container_name: cesizen_api
    image: ghcr.io/votre-username/cesizen-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=cesizen_db,1433;Database=CESIZenDatabase;User Id=sa;Password=${SQL_SERVER_PASSWORD:-Strong!Passw0rd};TrustServerCertificate=true;
    ports:
      - "5000:80"
    depends_on:
      cesizen_db:
        condition: service_healthy
    restart: unless-stopped

  cesizen_ui:
    container_name: cesizen_ui
    image: ghcr.io/votre-username/cesizen-ui:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=cesizen_db,1433;Database=CESIZenDatabase;User Id=sa;Password=${SQL_SERVER_PASSWORD:-Strong!Passw0rd};TrustServerCertificate=true;
    ports:
      - "80:80"
    depends_on:
      cesizen_db:
        condition: service_healthy
      cesizen_api:
        condition: service_started
    restart: unless-stopped

  nginx:
    container_name: cesizen_nginx
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - cesizen_ui
      - cesizen_api
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local